{% extends layout %}
{% block title %}Edit {{ $employee->first_name }} {{ $employee->surname }}{% endblock %}
{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script type="module" src="//<?=env('app.host')?>/<?=env('app.name')?>/app/assets/js/Employee.js"></script>
    <link rel="stylesheet" href="//<?=env('app.host')?>/<?=env('app.name')?>/app/assets/css/mSelect.css">
{% endblock %}

{% block content %}
<form id="employee_form" action="//<?=env('app.host')?>/<?=env('app.name')?>/Employee/update" method="POST">
    <div id="form_errors" style="display: none">
        
    </div>
    <div class="form-field">
        <label for="first_name">First name:*</label>
        <input validate="isRequired" required="required" type="text" id="first_name" name="first_name" value="{{ $employee->first_name }}"/>
        <small></small>
    </div>
    <div class="form-field">
        <label for="surname">Last name:</label>
        <input type="text" id="surname" name="surname" value="{{ $employee->surname }}">
        <small></small>
    </div>
    <div class="form-field">
        <label for="email">Enail:*</label>
        <input validate="isEmailValid" type="email" required="required" id="email" name="email" value="{{ $employee->email }}">
        <small></small>
    </div>
    <div class="form-field">
        <label for="contact_number">Contact Number:</label>
        <input type="text" type="tel" id="contact_number" name="contact_number" value="{{ $employee->contact_number }}">
        <small></small>
    </div>
    <div class="form-field">
        <label for="start_date">Start Date:</label>
        <input type="text" readonly="readonly" id="start_date" name="start_date" value="{{ $employee->start_date }}">
        <small>This field can not be updated</small>
    </div>
    <div class="form-field">
        <label for="active" style="display:block">Active:</label>
        <input validate="isChecked" type="checkbox" id="active" name="active" value="{{ $employee->active }}" {% if ($employee->active == 1): %}checked="checked"{% endif; %}>
        <small></small>
    </div>
    <div class="form-field">
        <label for="employee_code">Employee Code:*</label>
        <input type="text" required="required" id="employee_code" name="employee_code" value="{{ $employee->employee_code }}">
        <small></small>
    </div>

    <div >
        <label for="employee_groups">Employee Grups:</label>
        <div id="MSelectContainer">
            <select id="employee_groups"  class="form-control" name="employee_groups[]" multiple="multiple">
            {% foreach($groups as $group): %}
                <option value="1" {% if (isset($employee->groups[$group->id])):%} selected="selected"{% endif %} >{{ $group->group_name }}</option>
            {% endforeach; %}
            </select>
        </div>
    </div>
    <div class="form-field">
        <input type="hidden" name="id" value="{{ $employee->id }}">
        <input type="submit" value="Submit">
    </div>
</form>  
{% endblock %}