{% extends layout %}
{% block title %}Employee List{% endblock %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Surname
                </th>
                <th>
                    Email
                </th>
                <th>
                    Tel
                </th>
                <th>
                    Start Date
                </th>
                <th>
                    Active
                </th>
                <th>
                    Code
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% foreach($employees as $person): %}
           
            <tr>
                <td>{{ $person['first_name'] }}</td>
                <td>{{ $person['surname'] }}</td>
                <td>{{ $person['email'] }}</td>
                <td>{{ $person['contact_number'] }}</td>
                <td>{{ $person['start_date'] }}</td>
                <td>{{ $person['active'] }}</td>
                <td>{{ $person['employee_code'] }}</td>
                <td><a href="//<?=env('app.host')?>/<?=env('app.name')?>/employee/edit/{{ $person['id'] }}">Edit</a></td>
            </tr>
            {% endforeach; %}
        </tbody>
    </table>   
{% endblock %}